"""cut-043 — KM rule pure-function unit tests (no DB, no API).

Mirrors `tests/unit/test_v0_rule_and_decision.py` (procurement S3 criterion)
to lock the R-KM-ACCESS contract at the unit level. Codex discipline: write
the binding contract for the rule's three gates — pure functions, fixed
condition order, six keys per condition, deterministic reason string.
"""
from __future__ import annotations

import re
import uuid

import pytest

from ece.context.assembly import ContextPackage
from ece.domain_packs.knowledge.agent.v0_rules import (
    DECISION_ID_PREFIX,
    RULE_ID,
    DECISION_KEY,
    build_decision,
    evaluate_rule_R_KM_ACCESS,
)

EXPECTED_CON_KEYS = ("name", "expr", "actual", "threshold", "passed", "claim")
CON_NAMES = ("policy_in_validity_window", "employee_has_read_permission")


def _context() -> ContextPackage:
    """Minimal ContextPackage stub for `build_decision`.

    We don't need a real assemble_context call here — the rule body does
    NOT touch `ctx` itself; only `build_decision` reads `package_id` and
    `request_id`. A stub keeps the unit test purely about the rule.
    """
    return ContextPackage(
        package_id=f"ctx_{uuid.uuid4()}",
        request_id=str(uuid.uuid4()),
        task={"intent": "evaluate_policy_question"},
        user={"id": "km-alice", "display_id": "km-alice", "roles": ["hr"]},
    )


# ---------------------------------------------------------------------------
# Criterion 4: rule always emits BOTH conditions, in fixed order, with 6 keys
# ---------------------------------------------------------------------------


def test_rule_emits_two_conditions_with_six_keys_each() -> None:
    conditions = evaluate_rule_R_KM_ACCESS(
        policy={
            "id": "KM-POL-001",
            "valid_from": "2026-01-01",
            "valid_to": "2026-12-31",
            "required_role": "hr",
        },
        employee={"id": "km-alice", "roles": ["hr"]},
        today="2026-09-22",
    )

    assert len(conditions) == 2, f"expected 2 conditions, got {len(conditions)}"
    assert tuple(c["name"] for c in conditions) == CON_NAMES, (
        f"condition order is fixed: {CON_NAMES}; got {[c['name'] for c in conditions]}"
    )
    for cond in conditions:
        assert set(cond.keys()) == set(EXPECTED_CON_KEYS), (
            f"condition must have exactly 6 keys {EXPECTED_CON_KEYS}; got {set(cond.keys())}"
        )


# ---------------------------------------------------------------------------
# Criterion 5: module purity — no sqlalchemy / Engine imports
# ---------------------------------------------------------------------------


def test_module_purity_no_sqlalchemy_no_engine() -> None:
    """S3 criterion 5 — rule module MUST NOT import DB-driver."""
    import ece.domain_packs.knowledge.agent.v0_rules as mod

    src = open(mod.__file__, "r", encoding="utf-8").read()
    assert "import sqlalchemy" not in src and "from sqlalchemy" not in src, (
        "rule module must be pure (no sqlalchemy import); see S3 criterion 5"
    )
    assert "Engine(" not in src, "rule module must not hold a DB handle"


# ---------------------------------------------------------------------------
# Determinism: N=10 calls produce byte-equal output
# ---------------------------------------------------------------------------


def test_rule_byte_equal_across_10_calls() -> None:
    """S3 determinism contract — the rule must be pure across N=10 calls."""
    policy = {
        "id": "KM-POL-001",
        "valid_from": "2026-01-01",
        "valid_to": "2026-12-31",
        "required_role": "hr",
    }
    employee = {"id": "km-alice", "roles": ["hr"]}
    today = "2026-09-22"

    first = evaluate_rule_R_KM_ACCESS(policy, employee, today)
    for _ in range(9):
        again = evaluate_rule_R_KM_ACCESS(policy, employee, today)
        assert again == first, (
            "rule must be deterministic across calls; got non-equal output"
        )

    # decision_id is generated by build_decision; assert it's fresh each time
    # but contains the expected prefix.
    decision = build_decision(first, _context())
    assert decision["decision_id"].startswith(DECISION_ID_PREFIX), (
        f"decision_id must start with {DECISION_ID_PREFIX!r}; got {decision['decision_id']!r}"
    )


# ---------------------------------------------------------------------------
# Boundary matrix: truth-table completeness (answerable vs needs_valid_policy)
# ---------------------------------------------------------------------------


_BOUNDARY_MATRIX: list[tuple[str, str, str, list[str], str]] = [
    # (policy_id, valid_from, valid_to, employee_roles, today, expected_value)
    # validity pass + perm pass → answerable
    ("KM-POL-001", "2026-01-01", "2026-12-31", ["hr"], "2026-09-22", "answerable"),
    # validity fail (expired) + perm pass → needs_valid_policy
    ("KM-POL-002", "2024-01-01", "2024-12-31", ["hr"], "2026-09-22", "needs_valid_policy"),
    # validity pass + perm fail (missing role) → needs_valid_policy
    ("KM-POL-003", "2026-01-01", "2026-12-31", ["hr"], "2026-09-22", "needs_valid_policy"),
    # validity pass + perm fail (no roles) → needs_valid_policy
    ("KM-POL-001", "2026-01-01", "2026-12-31", [], "2026-09-22", "needs_valid_policy"),
    # edge: today == valid_from (start-of-window inclusive)
    ("KM-POL-001", "2026-09-22", "2026-12-31", ["hr"], "2026-09-22", "answerable"),
    # edge: today == valid_to (end-of-window exclusive)
    ("KM-POL-001", "2026-01-01", "2026-09-22", ["hr"], "2026-09-22", "needs_valid_policy"),
]


@pytest.mark.parametrize(
    ("policy_id", "valid_from", "valid_to", "roles", "today", "expected_value"),
    _BOUNDARY_MATRIX,
)
def test_rule_truth_table_decision_value(
    policy_id: str,
    valid_from: str,
    valid_to: str,
    roles: list[str],
    today: str,
    expected_value: str,
) -> None:
    """Criterion 2: 6 cases covering the rule's truth-table boundaries."""
    conditions = evaluate_rule_R_KM_ACCESS(
        policy={
            "id": policy_id,
            "valid_from": valid_from,
            "valid_to": valid_to,
            "required_role": "hr" if policy_id != "KM-POL-003" else "finance",
        },
        employee={"id": "km-alice", "roles": roles},
        today=today,
    )
    decision = build_decision(conditions, _context())
    assert decision["decision_value"] == expected_value, (
        f"policy_id={policy_id} roles={roles} today={today}: "
        f"expected {expected_value}, got {decision['decision_value']!r}"
    )
    assert decision["rule_id"] == RULE_ID
    assert decision["decision_key"] == DECISION_KEY


# ---------------------------------------------------------------------------
# Reason string is byte-equal across calls and free of time/UUID leakage
# ---------------------------------------------------------------------------


def test_reason_string_is_pure_and_free_of_time_uuid() -> None:
    conditions = evaluate_rule_R_KM_ACCESS(
        policy={
            "id": "KM-POL-001",
            "valid_from": "2026-01-01",
            "valid_to": "2026-12-31",
            "required_role": "hr",
        },
        employee={"id": "km-alice", "roles": ["hr"]},
        today="2026-09-22",
    )
    decision = build_decision(conditions, _context())
    reason = decision["reason"]

    # Pure: no datetime / uuid / timestamp substrings.
    assert not re.search(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}", reason), (
        f"reason leaked datetime; got: {reason!r}"
    )
    assert "uuid" not in reason.lower(), f"reason leaked uuid word; got: {reason!r}"
